steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f=docker/Dockerfile'
  - '--tag=gcr.io/${PROJECT_ID}/aag-weather'
  - '.'

# Push to Container Registry
images:
- 'gcr.io/$PROJECT_ID/aag-weather'
